const assert=require('node:assert/strict');
global.window={};
require('../settings.js');
const {matches,validate}=window.SpotSettings;
const defaults={pilot:'2026-09-28',thCrit:55,thHaute:30,thMoy:12,etaCrit:-7,rtaCrit:-7,sla:{docs:2},sevColors:{Haute:'#e9730c'},alerts:{A1:{t:'ETA',sev:'Critique',w:30,days:0,c:'#d92d20',on:true,h:''}}};
const rule={t:'Retard sans BAE',sev:'Haute',w:15,days:0,c:'#e9730c',on:true,mode:'all',conditions:[{field:'dateETA',op:'olderThan',value:3},{field:'dateBAE',op:'empty',value:''}]};
const pilot=new Date('2026-09-28T00:00:00');
const row={dateETA:new Date('2026-09-20T00:00:00'),dateBAE:null};
assert.equal(matches(rule,row,pilot),true);
assert.equal(matches(rule,{...row,dateBAE:new Date()},pilot),false);
assert.equal(matches(rule,{...row,dateETA:null},pilot),false);
assert.equal(matches({...rule,mode:'any'},{...row,dateBAE:new Date()},pilot),true);
assert.equal(matches({conditions:[{field:'delaiETA',op:'lt',value:-7}]},{delaiETA:0},pilot),false);
assert.equal(matches({conditions:[{field:'delaiETA',op:'present'}]},{delaiETA:0},pilot),true);
const config=validate({...defaults,alerts:{...defaults.alerts,R1:rule}},defaults);
const restored=validate(JSON.parse(JSON.stringify({format:'spot-settings',version:1,settings:config})),defaults);
assert.deepEqual(restored,config);
assert.equal(matches(restored.alerts.R1,row,pilot),true);
const hidden=validate({...config,alerts:{...config.alerts,A1:{...config.alerts.A1,on:false,deleted:true}}},defaults);
assert.equal(hidden.alerts.A1.deleted,true);
assert.equal(hidden.alerts.A1.on,false);
assert.throws(()=>validate({...config,thCrit:5},defaults),/Seuils/);
assert.throws(()=>validate({format:'spot-settings',version:2,settings:config},defaults),/Version/);
assert.throws(()=>validate({...config,alerts:{R1:{...rule,conditions:[{field:'__proto__',op:'eq',value:'x'}]}}},defaults),/Champ/);
assert.throws(()=>validate({...config,alerts:{R1:{...rule,conditions:[{field:'client',op:'olderThan',value:3}]}}},defaults),/champ date/);
assert.throws(()=>validate({...config,alerts:{R1:{...rule,c:'red'}}},defaults),/couleur/);
assert.throws(()=>validate({...config,alerts:{R1:{...rule,conditions:[]}}},defaults),/Conditions/);
console.log('PASS: conditions ET/OU, dates manquantes, zéro numérique, JSON aller-retour, masquage/suppression, validation des fichiers');
